from flask import Flask, Response
from flask_compress import Compress
import cv2

app = Flask(__name__)
Compress(app)  

cap = cv2.VideoCapture(0, cv2.CAP_DSHOW) 
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

@app.route('/')
def index():
    return "Video feed endpoint accessed"

def generate_frames():
    frame_skip = 2  
    count = 0

    while True:
        success, frame = cap.read()
        if not success:
            break
        if count % frame_skip == 0:
            ret, buffer = cv2.imencode('.jpg', frame, [cv2.IMWRITE_JPEG_QUALITY, 70])
            frame = buffer.tobytes()

            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
        count += 1

@app.route('/video_feed')
def video_feed():
    # Return the response generated by generate_frames
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
